apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2018-04-04T20:27:53Z
  labels:
    run: bad-java-test-app-demo
  name: bad-java-test-app-demo
  namespace: bad-java-test-app
  resourceVersion: "7652008"
  selfLink: /api/v1/namespaces/bad-java-test-app/services/bad-java-test-app-demo
  uid: a6f8eeb8-3846-11e8-9247-005056a4e657
spec:
  clusterIP: 172.30.189.110
  externalIPs:
  - 172.29.54.215
  externalTrafficPolicy: Cluster
  ports:
  - name: bad-java-test-app-demo
    nodePort: 30264
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    run: bad-java-test-app-demo
  sessionAffinity: ClientIP
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 172.29.54.215
